### ISSUE TITLE
When rendering HTML with styleType: 'css', one text block cannot be both underline and strikethrough

### ISSUE THREAD

**Issue by kbjr** [UmbraEngineering/quilljs-renderer#1]
Underlines and strikethroughs are both handled by `text-decoration` in css, which means one node cannot have both. This could be fixed by wrapping it in a second element, like this:

``` html
<span style="text-decoration: underline">
  <span style="text-decoration: line-through">
    content
  </span>
</span>
```

**Comment by kbjr** [comment]
This can now (theoretically) be fixed as the `text-decoration` property can now take multiple values:

```css
element {
    text-decoration-line: underline line-through;
}
```
